@extends('layouts.admin')
@section('heading','Profil, Kontak & Shopee')
@section('content')
<form method="POST" enctype="multipart/form-data" action="{{ route('admin.settings.update') }}" class="grid gap-7 xl:grid-cols-2">@csrf @method('PUT')
<section class="card p-6"><h2 class="text-xl font-black">Profil Usaha</h2><div class="mt-6 space-y-5"><div><label class="label">Nama usaha</label><input class="field" name="business_name" value="{{ old('business_name',$profile->business_name) }}" required></div><div><label class="label">Logo</label><img src="{{ $profile->logo_url }}" class="mb-3 h-24 w-24 rounded-2xl object-cover"><input class="field" type="file" name="logo" accept="image/*"></div><div><label class="label">Deskripsi</label><textarea class="field" name="description" rows="4" required>{{ old('description',$profile->description) }}</textarea></div><div><label class="label">Sejarah singkat</label><textarea class="field" name="history" rows="4">{{ old('history',$profile->history) }}</textarea></div><div><label class="label">Alamat</label><textarea class="field" name="address" rows="3" required>{{ old('address',$profile->address) }}</textarea></div><div><label class="label">Jam operasional</label><input class="field" name="operational_hours" value="{{ old('operational_hours',$profile->operational_hours) }}" required></div></div></section>
<section class="space-y-7"><div class="card p-6"><h2 class="text-xl font-black">Kontak & Sosial Media</h2><div class="mt-6 space-y-5"><div><label class="label">WhatsApp</label><input class="field" name="whatsapp" value="{{ old('whatsapp',$contact->whatsapp) }}" required></div><div><label class="label">Instagram</label><input class="field" type="url" name="instagram" value="{{ old('instagram',$contact->instagram) }}"></div><div><label class="label">Email</label><input class="field" type="email" name="email" value="{{ old('email',$contact->email) }}"></div><div><label class="label">Google Maps</label><input class="field" type="url" name="maps_link" value="{{ old('maps_link',$contact->maps_link) }}"></div><div><label class="label">Link Shopee utama</label><input class="field" type="url" name="shopee_link" value="{{ old('shopee_link',$contact->shopee_link) }}"></div></div></div>
<div class="card p-6"><h2 class="font-black">QR Code Shopee</h2><div class="mt-4 inline-block rounded-2xl bg-white p-3">{!! QrCode::size(160)->generate($contact->shopee_link ?: route('home')) !!}</div><p class="mt-3 text-xs text-stone-400">QR diperbarui mengikuti link Shopee utama.</p></div><button class="btn-primary w-full">Simpan Pengaturan</button></section>
</form>
@endsection
